Added plugin for RACF KDFAES hashes
hashcat/hashcat pull request #3940
Opened 2024-01-29 21:58 UTC by c0rs

The plugin includes support for KDFAES password hashes used in z/OS. The hash algorithm is a IBM's proprietary implementation of PBKDF2-HMAC-SHA256.

The plugin is developed based on following PRs: 
- KDFAES implementation for earlier hashcat versions (https://github.com/hashcat/hashcat/pull/2777)
- KDFAES implementation for JtR (https://github.com/openwall/john/commit/bdf40440cb33398f07a99509ebeee32699d039c7)

2025-04-26 23:29 UTC, matrix requested changes
Hi @c0rs, after fix the code could you rename to 33400? Thanks

2025-04-26 23:29 UTC, matrix commented on OpenCL/m34000-pure.cl
> +DECLSPEC void convert_pbkdf2_sha256_from_V(pbkdf2_sha256_tmpx_t *tmpx, pbkdf2_sha256_tmp_t *tmps)
```
-DECLSPEC void convert_pbkdf2_sha256_from_V(pbkdf2_sha256_tmpx_t *tmpx, pbkdf2_sha256_tmp_t *tmps)
+DECLSPEC void convert_pbkdf2_sha256_from_V (PRIVATE_AS pbkdf2_sha256_tmpx_t *tmpx, PRIVATE_AS pbkdf2_sha256_tmp_t *tmps)
```

2025-04-26 23:29 UTC, matrix commented on OpenCL/m34000-pure.cl
> +DECLSPEC void convert_pbkdf2_sha256_to_V(pbkdf2_sha256_tmp_t *tmps, pbkdf2_sha256_tmpx_t *tmpx)
```
-DECLSPEC void convert_pbkdf2_sha256_to_V(pbkdf2_sha256_tmp_t *tmps, pbkdf2_sha256_tmpx_t *tmpx)
+DECLSPEC void convert_pbkdf2_sha256_to_V (PRIVATE_AS pbkdf2_sha256_tmp_t *tmps, PRIVATE_AS pbkdf2_sha256_tmpx_t *tmpx)
```

2025-04-26 23:29 UTC, matrix commented on OpenCL/m34000-pure.cl
> +DECLSPEC void racf_pbkdf_sha256_hmac_V(u32x *key, u32 key_len, u32x *salt, u32 salt_len, u32 iteration, pbkdf2_sha256_tmpx_t* tmpx)
```
-DECLSPEC void racf_pbkdf_sha256_hmac_V(u32x *key, u32 key_len, u32x *salt, u32 salt_len, u32 iteration, pbkdf2_sha256_tmpx_t* tmpx)
+DECLSPEC void racf_pbkdf_sha256_hmac_V (PRIVATE_AS u32x *key, u32 key_len, PRIVATE_AS u32x *salt, u32 salt_len, u32 iteration, PRIVATE_AS pbkdf2_sha256_tmpx_t* tmpx)
```

2025-04-26 23:29 UTC, matrix commented on OpenCL/m34000-pure.cl
> +  const u64 gid = get_global_id (0);
```
-  const u64 gid = get_global_id (0);
-  const u64 lid = get_local_id (0);
```

2025-04-26 23:29 UTC, matrix commented on OpenCL/m34000-pure.cl
> +  const u64 gid = get_global_id (0);
```
-  const u64 gid = get_global_id (0);
-  const u64 lid = get_local_id (0);
```

2025-05-06 09:45 UTC, c0rs commented on OpenCL/m34000-pure.cl
> +DECLSPEC void convert_pbkdf2_sha256_to_V(pbkdf2_sha256_tmp_t *tmps, pbkdf2_sha256_tmpx_t *tmpx)
done

2025-05-06 09:48 UTC, c0rs commented
Hi, @matrix ! Thank you for answer. I fixed the code and renamed the module according to your comments.

2025-05-06 18:02 UTC, matrix commented
> Hi, @matrix ! Thank you for answer. I fixed the code and renamed the module according to your comments.

Good. Last thing, if you share the results of test.sh, possibly both CPU and GPU. Thank!

2025-05-12 08:20 UTC, c0rs commented
[test_report_gpu.log](https://github.com/user-attachments/files/20157169/test_report_gpu.log)
[test_report_cpu.log](https://github.com/user-attachments/files/20157172/test_report_cpu.log)

2025-05-13 19:17 UTC, matrix commented
> Sure [test_report_gpu.log](https://github.com/user-attachments/files/20157169/test_report_gpu.log) [test_report_cpu.log](https://github.com/user-attachments/files/20157172/test_report_cpu.log)

Hi, you should try to do more tests and paste the output here, not the log file it produces.
minimal cmd for CPU: ./tools/test.sh -m 33400 -a all -t all -D1
minimal cmd for GPU: ./tools/test.sh -m 33400 -a all -t all -D2

Thanks

2025-05-14 08:36 UTC, c0rs commented
> > Sure [test_report_gpu.log](https://github.com/user-attachments/files/20157169/test_report_gpu.log) [test_report_cpu.log](https://github.com/user-attachments/files/20157172/test_report_cpu.log)
> 
> Hi, you should try to do more tests and paste the output here, not the log file it produces. minimal cmd for CPU: ./tools/test.sh -m 33400 -a all -t all -D1 minimal cmd for GPU: ./tools/test.sh -m 33400 -a all -t all -D2
> 
> Thanks

```
./tools/test.sh -m 33400 -a all -t all -D2
[ test_1747207627 ] > Init test for hash type 33400.
[ test_1747207627 ] [ Type 33400, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1747207627 ] [ Type 33400, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1747207627 ] [ Type 33400, Attack 0, Mode single, Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1747207627 ] [ Type 33400, Attack 0, Mode multi,  Device-Type Gpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```

```
./tools/test.sh -m 33400 -a all -t all -D1
[ test_1747208235 ] > Init test for hash type 33400.
[ test_1747208235 ] [ Type 33400, Attack 0, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1747208235 ] [ Type 33400, Attack 0, Mode multi,  Device-Type Cpu, Kernel-Type Optimized, Vector-Width 1 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
[ test_1747208235 ] [ Type 33400, Attack 0, Mode single, Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/8 not found, 0/8 not matched, 0/8 timeout, 0/8 skipped
[ test_1747208235 ] [ Type 33400, Attack 0, Mode multi,  Device-Type Cpu, Kernel-Type Optimized, Vector-Width 4 ] > OK : 0/1 not found, 0/1 not matched, 0/1 timeout, 0/1 skipped
```

[tests.zip](https://github.com/user-attachments/files/20203603/tests.zip)

2025-07-15 07:50 UTC, merged

2025-07-15 07:52 UTC, jsteube commented
Hey there, sorry for the delay. We do not see often LOOP2 kernels, so this is a complex kernel, very nice! Many thanks for the contribution.