Raise Bitwarden Iteration Limit
hashcat/hashcat pull request #3980
Opened 2024-04-02 21:35 UTC by PenguinKeeper7

Replace old 999,999 iteration cap with a larger cap to satisfy: https://hashcat.net/forum/thread-11885.html. Unknown if there is any Bitwarden-native cap on iterations.

2024-04-15 02:51 UTC, BaelfireNightshd commented
This doesn't appear to be able to load the hash (though it can from the benchmark). I ran the following command
`./hashcat -a 0 -m 23400 '$bitwarden$2*100000*2*bm9yZXBseUBoYXNoY2F0Lm5ldA==*+v5rHxYydSRUDlan+4pSoiYQwAgEhdmivlb+exQX+fg=' /usr/share/SecLists/Passwords/Leaked-Databases/rockyou.txt`
which uses the [same hash from the benchmark](https://github.com/PenguinKeeper7/hashcat/blob/29b39c5b832d7dab174d2589d4c06c3974eecc28/src/modules/module_23400.c#L30) and got the following output. 
```
 hashcat (v6.2.6) starting

* Device #1: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
* Device #2: WARNING! Kernel exec timeout is not disabled.
             This may cause "CL_OUT_OF_RESOURCES" or related errors.
             To disable the timeout, see: https://hashcat.net/q/timeoutpatch
The device #2 specifically listed was skipped because it is an alias of device #1

CUDA API (CUDA 12.4)
====================
* Device #1: NVIDIA GeForce RTX 3080, 8973/9999 MB, 68MCU

OpenCL API (OpenCL 3.0 CUDA 12.4.89) - Platform #1 [NVIDIA Corporation]
=======================================================================
* Device #2: NVIDIA GeForce RTX 3080, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hash '$bitwarden$2*100000*2*bm9yZXBseUBoYXNoY2F0Lm5ldA==*+v5rHxYydSRUDlan+4pSoiYQwAgEhdmivlb+exQX+fg=': Salt-iteration count exception
No hashes loaded.

Started: Sun Apr 14 19:46:10 2024
Stopped: Sun Apr 14 19:46:11 2024
```

2024-05-20 09:38 UTC, ventaquil requested changes

2024-05-20 09:38 UTC, ventaquil commented on src/modules/module_23400.c
> +  if (iter1 > 10^10) return (PARSER_SALT_ITERATION);
`^` is xor operator - take a look here https://en.cppreference.com/w/cpp/keyword/xor.

`iter1 > 10^10` will be compiled into `iter1 > 0` which almost always will be true.

2024-05-20 09:45 UTC, PenguinKeeper7 commented
Not sure how I didn't see this, thanks. Must've been something I added after testing to simplify the code a bit

2024-05-20 14:52 UTC, ventaquil commented
What do you think about creating some consts like `ITER_DIGITS_MIN`/`ITER_DIGITS_MAX`?

```c
const static unsigned ITER_DIGITS_MIN = 1;
const static unsigned ITER_DIGITS_MAX = 10;

// validate with those values
const unsigned iter_min = pow(10, ITER_DIGITS_MIN - 1);
const unsigned iter_max = pow(10, ITER_DIGITS_MAX - 1);
if (iter1 < iter_min) return (PARSER_SALT_ITERATION);
if (iter1 > iter_max) return (PARSER_SALT_ITERATION);
```

2024-05-20 15:01 UTC, PenguinKeeper7 commented
Well, it's just set to int-max for now. The kernel itself would have to be re-designed if you wanted to go higher and there could potentially be accidental accuracy/overflow issues if you do go higher than u32 and it's not caught. Defining consts would only be purely a readability thing, it wouldn't enable easy future expansion

2024-05-20 15:23 UTC, ventaquil commented
Hmm... Well, isn't it simpler to use `const static unsigned INTMAX = ~0`? Maybe with a tiny comment why this value was chosen.

It's more about readability rather than option to quick and easy increase iter size.

2024-05-20 21:16 UTC, ventaquil commented on src/modules/module_23400.c
> +  if (iter1 > UINT_MAX) return (PARSER_SALT_ITERATION);
`iter1` is `u32` so condition `1 <= iter1 <= UINT_MAX` isn't just `iter != 0`?

Is it possible to store more than `UINT_MAX` in `iter1`?

```suggestion
  if (iter1 == 0) return (PARSER_SALT_ITERATION);
```

2025-07-14 18:47 UTC, merged